package com.elixr.hinachos.server.dto;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class HiNachosRewardsSummaryDataItem {
    private Object rank;
    private String type;
    private String userId;
    private String name;
    private String hashTagId;
    private Long totalRewards;

    public HiNachosRewardsSummaryDataItem() {

    }

    public HiNachosRewardsSummaryDataItem(Object rank, String type, String userId, String name, Long totalRewards) {
        this.rank = rank;
        this.type = type;
        this.userId = userId;
        this.name = name;
        this.totalRewards = totalRewards;
    }
    public HiNachosRewardsSummaryDataItem(Object rank, String type, String userId, String name, String hashTagId, Long totalRewards) {
        this.rank = rank;
        this.type = type;
        this.userId = userId;
        this.name = name;
        this.hashTagId = hashTagId;
        this.totalRewards = totalRewards;
    }
    // Optional: Constructors, getters, and setters can be generated by Lombok
}
